config/routes.rb
SociaLoginRails::Application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  get "pages/terms"
  get "pages/welcome"
  get "pages/landing"

  resources :users do
    resources :widgets do
      collection {post :sort}
    end

  end

  root :to => 'pages#landing'
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  belongs_to :user
  has_one :widget

  after_create :fetch_details

  def refresh_auth_token
    data = {
      client_id: ENV['GOOGLE_KEY'],
      client_secret: ENV['GOOGLE_SECRET'],
      refresh_token: refresh_token,
      grant_type: 'refresh_token'
    }
    response = ActiveSupport::JSON.decode(RestClient.post('https://accounts.google.com/o/oauth2/token', data))

    if response['access_token'].present?
      update_attributes(
        token: response['access_token'],
        expires_at: Time.now + response['expires_in'].to_i.seconds
      ).to_i
    end
  rescue RestClient::BadRequest => e
  # Bad request
  rescue StandardError
    # else bad happened
  end

  def expired?
    Time.at(expires_at) < Time.now
  end

  def fresh_token
    refresh_auth_token if expired?
    token
  end

  def fetch_details
    send("fetch_details_from_#{provider.downcase}")
  end

  def fetch_details_from_facebook
    graph = Koala::Facebook::API.new(token)
    facebook_data = graph.get_object('me')
    self.username = facebook_data['username']
    save
  end

  def fetch_details_from_twitter; end

  def fetch_details_from_github; end

  def fetch_details_from_linkedin; end

  def fetch_details_from_google_oauth2; end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
      :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  #validates_presence_of :email
  mount_uploader :image, ImageUploader
  has_many :authorizations
  has_many :widgets


  def self.new_with_session(params,session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"],without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def self.from_omniauth(auth, current_user)

    authorization = Authorization.where(:provider => auth.provider, :uid => auth.uid.to_s).first_or_initialize
    authorization.token = auth.credentials.token
    authorization.secret = auth.credentials.secret
    authorization.refresh_token = auth.credentials.refresh_token
    authorization.expires_at = auth.credentials.expires_at
    authorization.expires = auth.credentials.expires

    if authorization.user.blank?
      user = current_user || User.where('email = ?', auth["info"]["email"]).first
      if user.blank?
       user = User.new
       user.password = Devise.friendly_token[0,10]
       user.name = auth.info.name
       user.email = auth.info.email
       if auth.provider == "twitter" 
         user.save(:validate => false)
       else
         user.save
       end
     end
     authorization.username = auth.info.nickname
     authorization.user_id = user.id
   end
    authorization.save
    authorization.user
  end
end

app/models/widget.rb
class Widget < ActiveRecord::Base

  before_create :set_col_position

  belongs_to :user
  belongs_to :authorization



  def set_col_position

    self.col =  1
    self.position = Widget.count
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

	skip_before_filter :authenticate_user!

	def all
		user = User.from_omniauth(env["omniauth.auth"], current_user)

		if user.persisted?
			flash[:notice] = "You are in! Go to edit profile to see the status for the accounts"
			sign_in_and_redirect(user)
		else
			session["devise.user_attributes"] = user.attributes
			redirect_to new_user_registration_url
		end
	end

	  def failure
      #handle you logic here..
      #and delegate to super.
      super
   end


	alias_method :facebook, :all
	alias_method :twitter, :all
	alias_method :linkedin, :all
	alias_method :github, :all
	alias_method :passthru, :all
	alias_method :google_oauth2, :all
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def terms
  end

  def welcome
  end

  def landing
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :set_user, only: [:show, :edit, :update]
  before_filter :validate_authorization_for_user, only: [:edit, :update]


  # GET /users/1
  def show
  end

  # GET /users/1/edit
  def edit
  end

  def index
    @users = User.all
  end

  # PATCH/PUT /users/1
  def update
    # 2015-07-23 RICHARD: Updated to use strong parameters
    if @user.update_attributes(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def validate_authorization_for_user
       redirect_to root_path unless @user == current_user
    end

    # 2015-07-23 RICHARD: Added to implement strong parameters
    def user_params
      params.require(:user).permit(:name, :user, :about, :image)
    end
  end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController

  before_filter :set_widget, only: [:show, :edit, :update, :destroy]

  def index

    @widgets = current_user.widgets.order("position")
    @result = []
    @widgets.each do |w|
      @result << self.send("fetch_#{w.authorization.provider}_data",w)
    end

  end

  def new
    @widget = Widget.new
  end

   def create

    @widget = current_user.widgets.new(widget_params)
    current_user.widgets << @widget
    @created_widget = self.send("fetch_#{@widget.authorization.provider}_data",@widget)
    if @widget.save {

      respond_to do |format|
        format.html {redirect_to user_widgets_path(current_user), :notice => "Widget created"}
        format.js {}
      end
    }
    else
      render "new"
    end
   end


  def update
    if  @widget.update_attributes(widget_params)
      respond_to do |format|
        format.js {}
        format.json {render status: 200}
      end
    end
  end

  def destroy

    @widget.destroy
    respond_to do |format|
      format.html { redirect_to  user_widgets_path(current_user)}
      format.js
    end

  end

  def sort

    params[:widget].each_with_index do |id, index|

      Widget.where(id: id).update_all(position: index+1)

    end
    render nothing: true
  end

  private

  def fetch_facebook_data(widget)

    auth = widget.authorization
    fb_api = Koala::Facebook::API.new(auth.token)
    fb_profile = fb_api.get_object("me?fields=name,picture,posts,link")

    {widget:widget, provider: auth.provider, fb_profile:fb_profile}

  end

  def fetch_twitter_data(widget)
    auth = widget.authorization
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV["TWITTER_KEY"]
      config.consumer_secret     = ENV["TWITTER_SECRET"]
      config.access_token        = auth.token
      config.access_token_secret = auth.secret
    end
    tw_user = client.user(auth.uid.to_i)
    tw_timeline = client.user_timeline(auth.uid.to_i)

    {widget:widget, provider: auth.provider, tw_user: tw_user, tw_timeline: tw_timeline }

  end

  def fetch_google_oauth2_data(widget)
    auth = widget.authorization
    GooglePlus.access_token = auth.fresh_token
       googlePerson = GooglePlus::Person.get(auth.uid)
       googleActivity = GooglePlus::Activity.for_person(auth.uid)

       {widget:widget, provider: auth.provider, google_persone: googlePerson, google_activity: googleActivity }
  end

  def set_widget

    @widget = Widget.find(params[:id])

  end


  def widget_params
    params.require(:widget).permit(:id,:title,:authorization_id,)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SociaLoginRails</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <a href="../" class="navbar-brand">Social Login</a>
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="navbar-collapse collapse" id="navbar-main">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="themes">DropDown <span class="caret"></span></a>
            <ul class="dropdown-menu" aria-labelledby="themes">
              <li><a tabindex="-1" href="/">Default</a></li>
              <li class="divider"></li>
              <li><a tabindex="-1" href="#/">Item 1</a></li>
              <li><a tabindex="-1" href="#/">Item 2</a></li>
              <li><a tabindex="-1" href="#/">Item 3</a></li>
              <li><a tabindex="-1" href="#/">Item 4</a></li>
              <li><a tabindex="-1" href="#/">Item 5</a></li>
              <li><a tabindex="-1" href="#/">Item 6</a></li>

            </ul>
          </li>
          <li>
            <%= link_to ' Widgets', user_widgets_path(current_user) if current_user %>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li><%= link_to current_user.name, current_user %></li>
          <li><%= link_to "Logout", destroy_user_session_path %></li>
          <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>

      </div>
    </div>
  </div>


  <div class="container" id="content">
   <div class="page-header" id="banner">
    <div class="row">
       <%= yield %>
    </div>
  </div>
</div>


</body>
</html>

app/views/pages/landing.html.erb
<h1 style="color:green">
<h2>Social widget app</h2>

app/views/pages/terms.html.erb
<h1>Pages#terms</h1>
<p>Find me in app/views/pages/terms.html.erb</p>

app/views/pages/welcome.html.erb
<h1>Pages#welcome</h1>
<p>Find me in app/views/pages/welcome.html.erb</p>

app/views/users/_form.html.erb
<%= simple_form_for @user, :html => { :multipart => true }  do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.file_field :image %>
    <%= f.input :name, :required => true, :autofocus => true %>
    <%= f.input :about, :required => true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<div>
Connect Account



<%# ['facebook', 'twitter', 'github', 'linkedin', 'google_oauth2'].each do |provider| %>

<% ['facebook', 'twitter', 'google_oauth2'].each do |provider| %>

  <% if current_user.authorizations.pluck(:provider).include?(provider.to_s) %>
    <%= provider.to_s.titleize %> Connected
  <% else %>
      <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path('user', provider) %>
  <% end %>
<br/>
<% end %>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
	  <%= (image_tag @user.image_url(:thumb).to_s, :style => "height: 100px" )%>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %>

app/views/widgets/_facebook.html.erb
 <div id="<%= "#{widget[:widget].id}" %>">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="well-sm">
          <%= link_to "", user_widget_path(current_user, widget[:widget]),
                      :method => :delete,
                      remote: true,
                      :data => {:confirm => 'Are you sure?'},
                      :class => 'btn btn-mini glyphicon glyphicon-remove pull-right' %>
          <div class="media">
            <a target="_blank" class="thumbnail pull-left" href="<%= widget[:fb_profile]['link'] %>">
              <img class="media-object" src="<%= widget[:fb_profile]['picture']['data']['url'] %>">
            </a>
            <div class="media-body">
              <h4 class="media-heading" style="padding: 5px">
                <a target="_blank" href="<%= widget[:fb_profile]['link'] %>">  <%= widget[:fb_profile]['name'] %></a>
                on Facebook </h4>
              <!--<p><span class="label label-info">888 photos</span> <span class="label label-warning">150 followers</span></p>-->
              <p>
                <!--<a href="#" class="btn btn-xs btn-default"><span class="glyphicon glyphicon-comment"></span> Message</a>-->
                <!--<a href="#" class="btn btn-xs btn-default"><span class="glyphicon glyphicon-heart"></span> Favorite</a>-->
                <!--<a href="#" class="btn btn-xs btn-default"><span class="glyphicon glyphicon-ban-circle"></span> Unfollow</a>-->
              </p>

              <p><b>New on my page</b></p>

              <p>
              <ol>
                <% widget[:fb_profile]['posts']['data'].each do |msg| %>

                    <% if msg['message'] %>
                        <li><%= msg['message'] %></li>
                    <% end %>
                <% end %>
              </p>
              </ol>
              <a target="_blank" href="<%= widget[:fb_profile]['link'] %>" class="pull-right">
                <span class="pull-right"> more details</span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/widgets/_form.html.erb
<div>
  <%= simple_form_for [current_user,@widget] , remote:true do |f| %>
      <%= f.input :title, placeholder: 'Name' %>
      <%= f.collection_select :authorization_id, current_user.authorizations,  :id, :provider, {} , class: 'form-control'  %>
      <%= f.button :submit, class: 'btn btn-primary btn-md' %>

  <% end %>
</div>

app/views/widgets/_google_oauth2.html.erb
<div id="<%= "#{widget[:widget].id}" %>">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class=" well-sm">
          <%= link_to "", user_widget_path(current_user, widget[:widget]),
                      :method => :delete,
                      remote: true,
                      :data => {:confirm => 'Are you sure?'},
                      :class => 'btn btn-mini glyphicon glyphicon-remove pull-right' %>
          <div class="media">
            <a target="_blank" class="pull-left" href="<%= widget[:google_persone].url %>">
              <img class="media-object img-circle" src="<%= widget[:google_persone].image.url %>">
            </a>
            <div class="media-body">
              <h4 class="media-heading" style="padding: 5px">
                <a target="_blank" href="<%= widget[:google_persone].url %>">  <%= "#{widget[:google_persone].name.given_name} #{widget[:google_persone].name.family_name}" %></a>
                <a target="_blank" class="btn btn-xs btn-default" href="<%= widget[:google_persone].url %>">
                  <div style="margin:4px 0 0 4px;" class="s7">
                    <div style="width:20px;height:20px;" class="ima Nr Rr">
                      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="20px" height="20px" viewBox="0 0 14 14" class="u7">
                        <path d="M12.5,6.2V4.7h-1.1v1.5H9.8v1.1h1.5v1.5h1.1V7.3H14V6.2H12.5z"></path>
                        <path d="M4.4,6.1v1.7h2.3c-0.2,1-1.1,1.8-2.3,1.8C3,9.6,1.8,8.4,1.8,7S3,4.4,4.4,4.4C5,4.4,5.6,4.6,6,5l1.3-1.3 C6.5,3.1,5.6,2.6,4.4,2.6C2,2.6,0,4.6,0,7s2,4.4,4.4,4.4c2.5,0,4.2-1.8,4.2-4.3c0-0.3,0-0.7-0.1-1C8.5,6.1,4.4,6.1,4.4,6.1z"></path>
                      </svg>
                    </div>
                  </div>
                  <span style="font-size:12px;line-height:28px;" class="hma t-Pa-mb-c-ha-oa" jsname="kjfY5b" dir="ltr">Подписаться</span>
                </a></h4>
              <p><b>New on my page</b></p>

              <p>
              <ol>
                <% widget[:google_activity].each do |msg| %>

                    <% if msg.object.content.present? %>
                        <li><a target="_blank" href="<%= msg.url %>"></li>
                        <%= msg.object.content %>
                        </a>
                    <% end %>
                <% end %>
              </p>
              </ol>
              </p>
              </p>
              <a target="_blank" href="<%= widget[:google_persone].url %>" class=" pull-right">
                <span class="">more details</span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/widgets/_twitter.html.erb
<div id="<%="#{widget[:widget].id}" %>" class="root timeline ltr customisable-border ">
  <div class="timeline-header customisable-border">
    <%=link_to "", user_widget_path(current_user, widget[:widget]),
               :method => :delete,
               remote: true,
               :data => { :confirm => 'Are you sure?' },
               :class => 'btn btn-mini glyphicon glyphicon-remove ' %>
    <!--<h1 class="summary">-->
      <!--<a class="customisable-highlight" href="https://twitter.com/<%#= widget[:tw_user].screen_name %>" title="Твиты от <%#= widget[:tw_user].name %>">Твиты</a>-->
    <!--</h1>-->
    <a target="_blank" class="follow-button profile" href="https://twitter.com/<%= widget[:tw_user].screen_name %>" title="Читать <%= widget[:tw_user].name %> в Твиттере"><i class="ic-button-bird"></i>Читать</a>
  </div>
  <div class="new-tweets-bar">
  </div>
  <div class="stream" style="height: auto; width: auto;">
    <ol class="h-feed">
      <%  widget[:tw_timeline].each do |msg| %>

          <% if msg.text %>

      <li class="h-entry tweet js-tweetIdInfo customisable-border">
        <div class="header">
          <div class="h-card p-author">
            <a target="_blank" class="u-url profile" href="https://twitter.com/<%= widget[:tw_user].screen_name %>">
              <img class="u-photo avatar" alt="" src="<%= widget[:tw_user].profile_image_url%>" >
              <span class="full-name">
                <span class="p-name customisable-highlight"><%= widget[:tw_user].name %></span>
                </span>
              <span class="p-nickname">@<b><%= widget[:tw_user].screen_name %></b></span>
            </a>
          </div>
        </div>
        <div class="e-entry-content">
          <p class="e-entry-title"><%= msg.text %></p>
        </div>
        <div class="footer customisable-border">
          <ul class="tweet-actions">
            <li><a target="_blank" href="https://twitter.com/intent/tweet?in_reply_to=<%= msg.id %>" class="reply-action web-intent" title="Ответить"><i class="ic-reply ic-mask"></i><b>Ответить</b></a></li>
            <li><a target="_blank" href="https://twitter.com/intent/retweet?tweet_id=<%= msg.id %>" class="retweet-action web-intent" title="Ретвитнуть"><i class="ic-retweet ic-mask"></i><b>Ретвитнуть</b></a></li>
            <li><a target="_blank" href="https://twitter.com/intent/favorite?tweet_id=<%= msg.id %>" class="favorite-action web-intent" title="В избранное"><i class="ic-fav ic-mask"></i><b>В избранное</b></a></li>
          </ul>
        </div>
      </li>
          <%end %>
      <%end%>
    </ol>
  </div>
  <div class="timeline-footer">
    <a target="_blank" class="tweet-box-button web-intent" href="https://twitter.com/intent/tweet?screen_name=<%= widget[:tw_user].screen_name %>">Отправить твит @<%= widget[:tw_user].screen_name %></a>
  </div>
</div>

app/views/widgets/_widget.html.erb
<div class="portlet ui-widget ui-widget-content ui-helper-clearfix ui-corner-all"
     data-widget_id="<%= wdg[:widget].id %>">
  <div class="portlet-header ui-widget-header ui-corner-all">

          <span class='ui-icon ui-icon-<%=wdg[:widget].state ? 'minusthick' : 'plusthick' %> portlet-toggle'
                data-update-url="<%= widgetState_user_widgets_url %>"
                data-widget_id="<%= wdg[:widget].id %>">

          </span>
    <span style="display: inline-block">
          <%= link_to "", user_widget_path(current_user, wdg[:widget]),
                :method => :delete,
                remote: true,
                :data => {:confirm => 'Are you sure?'},
                :class => 'ui-icon ui-icon-close' %>
</span>
    <%= "#{wdg[:widget].title}" %></div>
  <div class="portlet-content <%=wdg[:widget].state ? '' : 'hidden' %>"
       data-content-url="<%= getWidgetData_user_widget_url(current_user,wdg[:widget].id)%>">
  <i class="fa fa-3x fa-spinner fa-spin col-lg-offset-5"></i>
  </div>
</div>

app/views/widgets/create.js.erb
$('#createNewWidget').popover("destroy");
var createdWidget = $("<%= j render "widget" , wdg:@created_widget %>")
$('.column').first().append(createdWidget);
loadWidgetContentIfVisible(createdWidget);
onFirstExpandWidget(createdWidget);
createdWidget.find(".portlet-toggle").click(function () {
    onToggleWidgetContent(this)
});

app/views/widgets/destroy.js.erb
$(".portlet[data-widget_id=\"<%= @widget.id %>\"]").remove();

app/views/widgets/index.html.erb
<div  id="mainContent">
<h1>Social Widgets</h1>

  <ul id="sortable" data-update-url="<%= sort_user_widgets_url %>">
    <% @result.each do |wdg| %>

       <%= content_tag_for :li, wdg[:widget] do  %>
        <%= render "#{wdg[:provider]}", widget:wdg  if wdg%>

        <% end %>
    <% end %>
  </ul>
</div>
<%= link_to "Add widget", new_user_widget_path(current_user), remote:true , id:"createNewWidget", data:{toggle:"popover", container:"body"}, class:"btn btn-md btn-primary" %>

<script>

    $(function() {
        $( "#sortable" ).sortable({
            axis: 'y',
            cursor: 'move',
            revert: true,
            update: function(e, ui) {
                $.post($(this).data('update-url'),$(this).sortable('serialize'))
            }
        });
        $( "ul, li" ).disableSelection();
    });
</script>

app/views/widgets/new.js.erb
$('#createNewWidget').popover("destroy");
$('#createNewWidget').popover({
    html:true,
    content:"<%= j render 'form'%>",
    placement:"bottom",
    container:"body",
    template:'<div style="width: 500px;" class="popover" role="tooltip"><div class="popover-content"></div></div>'

}).popover('show');